###################################################################
# JDevs                     v1.0.0                      Christmas #
# Christmas                                                 JDevs #
###################################################################
version: 1.0.0 # При обновлении плагина, данная настройка может помочь обновить конфигурацию за вас. (Не удалять)

# Значения:
# true - Включить
# false - Выключить
# null - Поставьте это, когда вам не нужно данное сообщение в чате

# Получить информацию о командах:
# /gifts

settings:
  gift: # Настройки подарка
    # Текстура головы base64 для подарка
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmNlZjlhYTE0ZTg4NDc3M2VhYzEzNGE0ZWU4OTcyMDYzZjQ2NmRlNjc4MzYzY2Y3YjFhMjFhODViNyJ9fX0="
    limit: true # Лимит на подарки
    max: 5 # Максимальное количество подарков с лимитом
    remove: 30 # В секундах. Через сколько удаляется подарок, если он не был использован.
    spawn:
      # // Установите null, чтобы плагин заменил данные настройки на свои
      type: null # Для версий 1.13+ (Настройка FallBlock по имени материала) Пример: "BARREL"
      id: null # Для версий ...-1.12.2 (Настройка FallBlock по id материала) Пример: "5"
      firework: true # Использовать фейерверки?
      timeLived: 10 # В секундах. Сколько будет длиться жизнь FallBlock, если он не будет задействован?
  grinch: # Настройки гринча
    enabled: true # Включить?
    chance: 20 # Шанс на подарок от гринча
  loot: # Настройки ресурсов
    enabled: true # Включить?
    taked: false # Если подарок не был получен, то лут автоматически выпадает из него (Также при выключении)
  holograms: # Настройки голограммы
    enabled: true # Включить голограмму во время появления подарка?
    height: 1.2 # Высота для голограммы
    lines: # Строки голограммы
      - "&cПодарок"
      - "&fНажми ПКМ, чтобы открыть!"
actions:
  # Действия:
  # [message] сообщение - Отправить сообщение игроку.
  # [broadcast] сообщение - Отправить сообщение всему серверу.
  # [player] команда - Выполнить команду от имени игрока.
  # [console] команда - Выполнить команду от имени консоли.
  # [sound] sound;volume;pitch - Выполнить звук для игрока
  # Звуки искать тут: https://helpch.at/docs/версия/org/bukkit/Sound.html
  # // Замените "версия" на версию вашего сервера, к примеру: https://helpch.at/docs/1.8/org/bukkit/Sound.html
  #
  # Встроенные функции:
  # %player% - Получить имя игрока
  # %rnd_player% - Получить имя случайного игрока
  gift: # При появлении подарка
    spawn:
      - "[message] &f"
      - "[message] &f&l✽ &aОт &aСанты Клауса&f пришел вам &cподарок &f— &cС новым годом! &f&l✽"
      - "[message] &f"
    loss: # При потере подарка
      - "[message] &f"
      - "[message] &f&l✽ &aСанта Клаус&f забрал &cподарок &f— &cТы забыл его забрать! &f&l✽"
      - "[message] &f"
    success: # Игрок успешно забрал подарок
      - "[message] &f&l✽ &r&fВы успешно забрали подарок"
    limit: # Игрок достиг лимита подарков
      - "[message] &f&l✽ &cВы уже забрали определённое кол-во подарков! :("
  no_perm: # У игрока нет прав
    - "[message] &f&l✽ &cУ вас недостаточно прав"

###############################################################
# JDevs                                             Christmas #
###############################################################